package openapisync

import "pebblepost/internal/types"

// DiffType indicates the status of an endpoint relative to the OpenAPI spec.
type DiffType string

const (
	DiffAdded     DiffType = "added"
	DiffRemoved   DiffType = "removed"
	DiffChanged   DiffType = "changed"
	DiffUnchanged DiffType = "unchanged"
)

// FieldDiff captures a change in a specific field between the spec and local file.
type FieldDiff struct {
	Field       string `json:"field"`       // method, url, parameters, body, auth
	OldValue    any    `json:"oldValue"`    // existing local value
	NewValue    any    `json:"newValue"`    // new spec value
	IsConflict  bool   `json:"isConflict"`  // true if local change conflicts with spec
	Description string `json:"description"` // human-readable explanation
}

// ConflictInfo details user assets that would be affected by a removal or breaking change.
type ConflictInfo struct {
	HasUserScripts       bool   `json:"hasUserScripts"`
	HasUserExamples      bool   `json:"hasUserExamples"`
	HasUserExtractors    bool   `json:"hasUserExtractors"`
	HasUserCustomHeaders bool   `json:"hasUserCustomHeaders"`
	Details              string `json:"details"`
}

// EndpointDiff represents the comparison between a spec operation and a local request file.
type EndpointDiff struct {
	ID               string                   `json:"id"` // Stable key: "METHOD /path"
	OperationID      string                   `json:"operationId,omitempty"`
	Summary          string                   `json:"summary,omitempty"`
	Method           string                   `json:"method"`
	Path             string                   `json:"path"`
	DiffType         DiffType                 `json:"diffType"`
	ExistingFilePath string                   `json:"existingFilePath,omitempty"`
	ProposedFilePath string                   `json:"proposedFilePath,omitempty"`
	FieldDiffs       []FieldDiff              `json:"fieldDiffs,omitempty"`
	Conflict         *ConflictInfo            `json:"conflict,omitempty"`
	SpecRequest      *types.RequestDefinition `json:"specRequest,omitempty"`
	ExistingRequest  *types.RequestDefinition `json:"existingRequest,omitempty"`
}

// SyncDiffReport is the structured report generated by comparing a spec with a folder.
type SyncDiffReport struct {
	FolderPath     string         `json:"folderPath"`
	SpecLocation   string         `json:"specLocation"`
	SpecHash       string         `json:"specHash"`
	TotalEndpoints int            `json:"totalEndpoints"`
	AddedCount     int            `json:"addedCount"`
	RemovedCount   int            `json:"removedCount"`
	ChangedCount   int            `json:"changedCount"`
	ConflictCount  int            `json:"conflictCount"`
	HasDrift       bool           `json:"hasDrift"`
	Endpoints      []EndpointDiff `json:"endpoints"`
}

// ApplyRequest specifies which changes from a SyncDiffReport to apply.
type ApplyRequest struct {
	FolderPath        string   `json:"folderPath"`
	SpecLocation      string   `json:"specLocation"`
	AcceptedEndpoints []string `json:"acceptedEndpoints,omitempty"` // IDs of endpoints to apply (empty = all non-conflicting)
	Force             bool     `json:"force,omitempty"`             // Apply conflicting removals
}

// ApplyResult summarizes the outcome of applying diff changes.
type ApplyResult struct {
	AppliedCount int      `json:"appliedCount"`
	SkippedCount int      `json:"skippedCount"`
	CreatedFiles []string `json:"createdFiles"`
	UpdatedFiles []string `json:"updatedFiles"`
	DeletedFiles []string `json:"deletedFiles"`
	NewSpecHash  string   `json:"newSpecHash"`
	SyncedAt     string   `json:"syncedAt"`
}

// LinkRequest specifies linking a folder to an OpenAPI specification.
type LinkRequest struct {
	FolderPath   string `json:"folderPath"`
	SpecLocation string `json:"specLocation"`
}
